/* Auto-generated by genmsg_cpp for file /home/rsd/groovy_workspace/FroboMind-Fuerte/fmMsgs/msg/can.msg */
#ifndef FMMSGS_MESSAGE_CAN_H
#define FMMSGS_MESSAGE_CAN_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace fmMsgs
{
template <class ContainerAllocator>
struct can_ {
  typedef can_<ContainerAllocator> Type;

  can_()
  : header()
  , flags(0)
  , cob(0)
  , id(0)
  , length(0)
  , data()
  {
    data.assign(0);
  }

  can_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , flags(0)
  , cob(0)
  , id(0)
  , length(0)
  , data()
  {
    data.assign(0);
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef int16_t _flags_type;
  int16_t flags;

  typedef int16_t _cob_type;
  int16_t cob;

  typedef uint32_t _id_type;
  uint32_t id;

  typedef int8_t _length_type;
  int8_t length;

  typedef boost::array<uint8_t, 8>  _data_type;
  boost::array<uint8_t, 8>  data;


  typedef boost::shared_ptr< ::fmMsgs::can_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fmMsgs::can_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct can
typedef  ::fmMsgs::can_<std::allocator<void> > can;

typedef boost::shared_ptr< ::fmMsgs::can> canPtr;
typedef boost::shared_ptr< ::fmMsgs::can const> canConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::fmMsgs::can_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::fmMsgs::can_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace fmMsgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::fmMsgs::can_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::fmMsgs::can_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::fmMsgs::can_<ContainerAllocator> > {
  static const char* value() 
  {
    return "a99deadd2ad5fffa3362639de81d27a3";
  }

  static const char* value(const  ::fmMsgs::can_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xa99deadd2ad5fffaULL;
  static const uint64_t static_value2 = 0x3362639de81d27a3ULL;
};

template<class ContainerAllocator>
struct DataType< ::fmMsgs::can_<ContainerAllocator> > {
  static const char* value() 
  {
    return "fmMsgs/can";
  }

  static const char* value(const  ::fmMsgs::can_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::fmMsgs::can_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
int16 flags\n\
int16 cob\n\
uint32 id\n\
int8 length\n\
uint8[8] data\n\
\n\
																		\n\
 \n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::fmMsgs::can_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::fmMsgs::can_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::fmMsgs::can_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::fmMsgs::can_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.flags);
    stream.next(m.cob);
    stream.next(m.id);
    stream.next(m.length);
    stream.next(m.data);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct can_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fmMsgs::can_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::fmMsgs::can_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "flags: ";
    Printer<int16_t>::stream(s, indent + "  ", v.flags);
    s << indent << "cob: ";
    Printer<int16_t>::stream(s, indent + "  ", v.cob);
    s << indent << "id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.id);
    s << indent << "length: ";
    Printer<int8_t>::stream(s, indent + "  ", v.length);
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.data[i]);
    }
  }
};


} // namespace message_operations
} // namespace ros

#endif // FMMSGS_MESSAGE_CAN_H

