/* Auto-generated by genmsg_cpp for file /home/rsd/groovy_workspace/FroboMind-Fuerte/fmMsgs/msg/joint_conf.msg */
#ifndef FMMSGS_MESSAGE_JOINT_CONF_H
#define FMMSGS_MESSAGE_JOINT_CONF_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace fmMsgs
{
template <class ContainerAllocator>
struct joint_conf_ {
  typedef joint_conf_<ContainerAllocator> Type;

  joint_conf_()
  : header()
  , enable(false)
  , joint1(0.0)
  , joint2(0.0)
  , joint3(0.0)
  , joint4(0.0)
  , tool(0.0)
  {
  }

  joint_conf_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , enable(false)
  , joint1(0.0)
  , joint2(0.0)
  , joint3(0.0)
  , joint4(0.0)
  , tool(0.0)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef uint8_t _enable_type;
  uint8_t enable;

  typedef double _joint1_type;
  double joint1;

  typedef double _joint2_type;
  double joint2;

  typedef double _joint3_type;
  double joint3;

  typedef double _joint4_type;
  double joint4;

  typedef double _tool_type;
  double tool;


  typedef boost::shared_ptr< ::fmMsgs::joint_conf_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fmMsgs::joint_conf_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct joint_conf
typedef  ::fmMsgs::joint_conf_<std::allocator<void> > joint_conf;

typedef boost::shared_ptr< ::fmMsgs::joint_conf> joint_confPtr;
typedef boost::shared_ptr< ::fmMsgs::joint_conf const> joint_confConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::fmMsgs::joint_conf_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::fmMsgs::joint_conf_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace fmMsgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::fmMsgs::joint_conf_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::fmMsgs::joint_conf_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::fmMsgs::joint_conf_<ContainerAllocator> > {
  static const char* value() 
  {
    return "bb024f6e37a203bc5faf223f196b5697";
  }

  static const char* value(const  ::fmMsgs::joint_conf_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xbb024f6e37a203bcULL;
  static const uint64_t static_value2 = 0x5faf223f196b5697ULL;
};

template<class ContainerAllocator>
struct DataType< ::fmMsgs::joint_conf_<ContainerAllocator> > {
  static const char* value() 
  {
    return "fmMsgs/joint_conf";
  }

  static const char* value(const  ::fmMsgs::joint_conf_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::fmMsgs::joint_conf_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
bool enable\n\
float64 joint1\n\
float64 joint2\n\
float64 joint3\n\
float64 joint4\n\
float64 tool\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::fmMsgs::joint_conf_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::fmMsgs::joint_conf_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::fmMsgs::joint_conf_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::fmMsgs::joint_conf_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.enable);
    stream.next(m.joint1);
    stream.next(m.joint2);
    stream.next(m.joint3);
    stream.next(m.joint4);
    stream.next(m.tool);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct joint_conf_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fmMsgs::joint_conf_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::fmMsgs::joint_conf_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "enable: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.enable);
    s << indent << "joint1: ";
    Printer<double>::stream(s, indent + "  ", v.joint1);
    s << indent << "joint2: ";
    Printer<double>::stream(s, indent + "  ", v.joint2);
    s << indent << "joint3: ";
    Printer<double>::stream(s, indent + "  ", v.joint3);
    s << indent << "joint4: ";
    Printer<double>::stream(s, indent + "  ", v.joint4);
    s << indent << "tool: ";
    Printer<double>::stream(s, indent + "  ", v.tool);
  }
};


} // namespace message_operations
} // namespace ros

#endif // FMMSGS_MESSAGE_JOINT_CONF_H

