/* Auto-generated by genmsg_cpp for file /home/rsd/groovy_workspace/FroboMind-Fuerte/fmMsgs/msg/lidar_safety_zone.msg */
#ifndef FMMSGS_MESSAGE_LIDAR_SAFETY_ZONE_H
#define FMMSGS_MESSAGE_LIDAR_SAFETY_ZONE_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace fmMsgs
{
template <class ContainerAllocator>
struct lidar_safety_zone_ {
  typedef lidar_safety_zone_<ContainerAllocator> Type;

  lidar_safety_zone_()
  : header()
  , yellow_activated(false)
  , red_activated(false)
  {
  }

  lidar_safety_zone_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , yellow_activated(false)
  , red_activated(false)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef uint8_t _yellow_activated_type;
  uint8_t yellow_activated;

  typedef uint8_t _red_activated_type;
  uint8_t red_activated;


  typedef boost::shared_ptr< ::fmMsgs::lidar_safety_zone_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fmMsgs::lidar_safety_zone_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct lidar_safety_zone
typedef  ::fmMsgs::lidar_safety_zone_<std::allocator<void> > lidar_safety_zone;

typedef boost::shared_ptr< ::fmMsgs::lidar_safety_zone> lidar_safety_zonePtr;
typedef boost::shared_ptr< ::fmMsgs::lidar_safety_zone const> lidar_safety_zoneConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::fmMsgs::lidar_safety_zone_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::fmMsgs::lidar_safety_zone_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace fmMsgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::fmMsgs::lidar_safety_zone_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::fmMsgs::lidar_safety_zone_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::fmMsgs::lidar_safety_zone_<ContainerAllocator> > {
  static const char* value() 
  {
    return "03b6c4958a90c0728cb0829888a7018d";
  }

  static const char* value(const  ::fmMsgs::lidar_safety_zone_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x03b6c4958a90c072ULL;
  static const uint64_t static_value2 = 0x8cb0829888a7018dULL;
};

template<class ContainerAllocator>
struct DataType< ::fmMsgs::lidar_safety_zone_<ContainerAllocator> > {
  static const char* value() 
  {
    return "fmMsgs/lidar_safety_zone";
  }

  static const char* value(const  ::fmMsgs::lidar_safety_zone_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::fmMsgs::lidar_safety_zone_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
bool yellow_activated\n\
bool red_activated\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::fmMsgs::lidar_safety_zone_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::fmMsgs::lidar_safety_zone_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::fmMsgs::lidar_safety_zone_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::fmMsgs::lidar_safety_zone_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.yellow_activated);
    stream.next(m.red_activated);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct lidar_safety_zone_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fmMsgs::lidar_safety_zone_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::fmMsgs::lidar_safety_zone_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "yellow_activated: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.yellow_activated);
    s << indent << "red_activated: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.red_activated);
  }
};


} // namespace message_operations
} // namespace ros

#endif // FMMSGS_MESSAGE_LIDAR_SAFETY_ZONE_H

