/* Auto-generated by genmsg_cpp for file /home/rsd/groovy_workspace/FroboMind-Fuerte/fmMsgs/msg/xyz_r_t.msg */
#ifndef FMMSGS_MESSAGE_XYZ_R_T_H
#define FMMSGS_MESSAGE_XYZ_R_T_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace fmMsgs
{
template <class ContainerAllocator>
struct xyz_r_t_ {
  typedef xyz_r_t_<ContainerAllocator> Type;

  xyz_r_t_()
  : header()
  , x(0.0)
  , y(0.0)
  , z(0.0)
  , phi(0.0)
  , tool(0.0)
  {
  }

  xyz_r_t_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , x(0.0)
  , y(0.0)
  , z(0.0)
  , phi(0.0)
  , tool(0.0)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef double _x_type;
  double x;

  typedef double _y_type;
  double y;

  typedef double _z_type;
  double z;

  typedef double _phi_type;
  double phi;

  typedef double _tool_type;
  double tool;


  typedef boost::shared_ptr< ::fmMsgs::xyz_r_t_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fmMsgs::xyz_r_t_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct xyz_r_t
typedef  ::fmMsgs::xyz_r_t_<std::allocator<void> > xyz_r_t;

typedef boost::shared_ptr< ::fmMsgs::xyz_r_t> xyz_r_tPtr;
typedef boost::shared_ptr< ::fmMsgs::xyz_r_t const> xyz_r_tConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::fmMsgs::xyz_r_t_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::fmMsgs::xyz_r_t_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace fmMsgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::fmMsgs::xyz_r_t_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::fmMsgs::xyz_r_t_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::fmMsgs::xyz_r_t_<ContainerAllocator> > {
  static const char* value() 
  {
    return "bf398ba5b0d5b9d5bfe117e6e5646607";
  }

  static const char* value(const  ::fmMsgs::xyz_r_t_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xbf398ba5b0d5b9d5ULL;
  static const uint64_t static_value2 = 0xbfe117e6e5646607ULL;
};

template<class ContainerAllocator>
struct DataType< ::fmMsgs::xyz_r_t_<ContainerAllocator> > {
  static const char* value() 
  {
    return "fmMsgs/xyz_r_t";
  }

  static const char* value(const  ::fmMsgs::xyz_r_t_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::fmMsgs::xyz_r_t_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 phi\n\
float64 tool\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::fmMsgs::xyz_r_t_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::fmMsgs::xyz_r_t_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::fmMsgs::xyz_r_t_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::fmMsgs::xyz_r_t_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.x);
    stream.next(m.y);
    stream.next(m.z);
    stream.next(m.phi);
    stream.next(m.tool);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct xyz_r_t_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fmMsgs::xyz_r_t_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::fmMsgs::xyz_r_t_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<double>::stream(s, indent + "  ", v.z);
    s << indent << "phi: ";
    Printer<double>::stream(s, indent + "  ", v.phi);
    s << indent << "tool: ";
    Printer<double>::stream(s, indent + "  ", v.tool);
  }
};


} // namespace message_operations
} // namespace ros

#endif // FMMSGS_MESSAGE_XYZ_R_T_H

