CATKIN_PACKAGE_PREFIX=""
PROJECT_ABSOLUTE_INCLUDE_DIRS="/usr/local/include;/opt/ros/groovy/include/opencv;/opt/ros/groovy/include"
PROJECT_CATKIN_DEPENDS="sensor_msgs"
PKG_CONFIG_LIBRARIES_WITH_PREFIX="-limage_geometry;-l:/opt/ros/groovy/lib/libopencv_calib3d.so;-l:/opt/ros/groovy/lib/libopencv_contrib.so;-l:/opt/ros/groovy/lib/libopencv_core.so;-l:/opt/ros/groovy/lib/libopencv_features2d.so;-l:/opt/ros/groovy/lib/libopencv_flann.so;-l:/opt/ros/groovy/lib/libopencv_gpu.so;-l:/opt/ros/groovy/lib/libopencv_highgui.so;-l:/opt/ros/groovy/lib/libopencv_imgproc.so;-l:/opt/ros/groovy/lib/libopencv_legacy.so;-l:/opt/ros/groovy/lib/libopencv_ml.so;-l:/opt/ros/groovy/lib/libopencv_nonfree.so;-l:/opt/ros/groovy/lib/libopencv_objdetect.so;-l:/opt/ros/groovy/lib/libopencv_photo.so;-l:/opt/ros/groovy/lib/libopencv_stitching.so;-l:/opt/ros/groovy/lib/libopencv_video.so;-l:/opt/ros/groovy/lib/libopencv_videostab.so"
PROJECT_NAME="image_geometry"
PROJECT_SPACE_DIR="/usr/local"
PROJECT_VERSION="1.10.6"
